### ISSUE TITLE
Boolean eliminators

### ISSUE THREAD

**Issue by brendanzab** [yeslogic/ddl#170]
We'll want to be able to check/compile something like this:

```
test = if true { true } else { false };
Test = if true { F64 } else { F32 };
```

I'm guessing the Rust compiler might emit different variants for each arm of the `if`. Eg.

```rust
enum Test {
    True(F64),
    False(F32),
}
```

**Comment by mikeday** [comment]
Would that not evaluate to `Test = F64`?

**Comment by brendanzab** [comment]
Depends on if we want our compiler to partially evaluate this stuff statically. I'm wary of doing this kind of thing right now, however!

**Comment by brendanzab** [comment]
At the moment I elaborate to unevaluated core syntax, then compile that to Rust/Docs/etc.

**Comment by brendanzab** [comment]
We could run into issues, however, if I claim that two terms are equal in my elaborator (using evaluation), but then they aren't in the generated Rust code. Not sure how to deal with this yet, though. Eg.

```
Test1 : Type = if true { F32 } else { F64 };
Test2 : Type = if false { F64 } else { F32 };
test1 : Test1 = 1.0;
test2 : Test2 = test1;
```

🤔

**Comment by brendanzab** [comment]
At the moment aliases are opaque so this wouldn't pass the elaborator, but once I allow them to be transparent (see #162), this could lead me to compile bad Rust code. 😬

**Comment by mikeday** [comment]
Currently we're taking a rather simplistic approach to Rust compilation, but that's something we can refine over time. I feel like rather than compiling module items one to one, the way to go is probably to define one or more entry points and compile the necessary dependencies, simplifying them as necessary.
