### ISSUE TITLE
Choose a better name than "DDL"

### ISSUE THREAD

**Issue by brendanzab** [yeslogic/ddl#5]
"DDL" is kind of.... boring. And it seems that the file extension is already taken, on Github at least!

**Comment by brendanzab** [comment]
- bitty/bitsy, itty-bitty/itsy-bitsy
- semblance, guise, veneer
- destruct: _dependent binary data structure description language_
- semblage: _semantic assemblages of bit data_

**Comment by adrianwong** [comment]
* deadlift - something something about doing the heavy lifting for you.
* deadlifted - suggested name change once deadlift is feature-complete.
* druidical - much mystical.
* doodle - because, well, you like to draw.
* cuddliest - variant of Michael's suggestion, but conveying with some passive-aggressive intent that no other DDL will be as cuddly.

**Comment by brendanzab** [comment]
Another idea:

- Fathom - understand (a difficult problem or an enigmatic person) after much thought

**Comment by wezm** [comment]
It's a different domain, but be aware of https://usefathom.com/ (was open-source analytics but then went closed-source in v2).

**Comment by brendanzab** [comment]
Ahh interesting - seems like there is also [mozilla/fathom](https://github.com/mozilla/fathom) - different domain too, but I think it has a little DSL attached?

**Comment by brendanzab** [comment]
kwak on the r/ProgrammingLanguages Discord suggests "Lambit":

> i liked the idea behind that one:
> > Lamdat (lambdas and data)
>
> though "lambit" sounds better to me
> with a cute lamb as a logo

**Comment by brendanzab** [comment]
TBH I think I'm rather leaning towards fathom - kind of what you must do when faced with a complicated binary format. Also mirrors the process of making the language itself! 😅
